-- MySQL Script generated by MySQL Workbench
-- Sat Feb 11 18:25:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `crm` ;

-- -----------------------------------------------------
-- Schema crm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm` DEFAULT CHARACTER SET utf8 ;
USE `crm` ;

-- -----------------------------------------------------
-- Table `crm`.`entreprise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`entreprise` (
  `siret` VARCHAR(30) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `code_postal` VARCHAR(45) NOT NULL,
  `url` VARCHAR(1000) NULL,
  `utilisateur_id` INT NOT NULL,
  PRIMARY KEY (`siret`, `utilisateur_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`poste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`poste` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idposte_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`statut` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`contact` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telephone` VARCHAR(30) NULL,
  `entreprise_siret` VARCHAR(45) NOT NULL,
  `poste_idposte` INT NULL,
  `statut_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_entreprise_idx` (`entreprise_siret` ASC),
  INDEX `fk_contact_poste1_idx` (`poste_idposte` ASC),
  INDEX `fk_contact_statut1_idx` (`statut_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_contact_entreprise`
    FOREIGN KEY (`entreprise_siret`)
    REFERENCES `crm`.`entreprise` (`siret`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_poste1`
    FOREIGN KEY (`poste_idposte`)
    REFERENCES `crm`.`poste` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_statut1`
    FOREIGN KEY (`statut_id`)
    REFERENCES `crm`.`statut` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`description`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`description` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_de_creation` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `description` VARCHAR(255) NOT NULL,
  `contact_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_description_contact1_idx` (`contact_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `fk_description_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `crm`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`utilisateur` (
  `siren` VARCHAR(20) NOT NULL,
  `nom_entreprise` VARCHAR(100) NOT NULL,
  `telephone` VARCHAR(30) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `iban` VARCHAR(27) NOT NULL,
  `adresse` VARCHAR(100) NOT NULL,
  `ville` VARCHAR(45) NOT NULL,
  `code_postal` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`siren`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`facture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`facture` (
  `num_facture` INT NOT NULL AUTO_INCREMENT,
  `date` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `utilisateur_siren` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`num_facture`),
  INDEX `fk_facture_utilisateur1_idx` (`utilisateur_siren` ASC),
  CONSTRAINT `fk_facture_utilisateur1`
    FOREIGN KEY (`utilisateur_siren`)
    REFERENCES `crm`.`utilisateur` (`siren`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`referencement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`referencement` (
  `entreprise_siret` VARCHAR(30) NOT NULL,
  `entreprise_utilisateur_id` INT NOT NULL,
  `utilisateur_siren` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`entreprise_siret`, `entreprise_utilisateur_id`, `utilisateur_siren`),
  INDEX `fk_entreprise_has_utilisateur_utilisateur1_idx` (`utilisateur_siren` ASC),
  INDEX `fk_entreprise_has_utilisateur_entreprise1_idx` (`entreprise_siret` ASC, `entreprise_utilisateur_id` ASC),
  CONSTRAINT `fk_entreprise_has_utilisateur_entreprise1`
    FOREIGN KEY (`entreprise_siret` , `entreprise_utilisateur_id`)
    REFERENCES `crm`.`entreprise` (`siret` , `utilisateur_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entreprise_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_siren`)
    REFERENCES `crm`.`utilisateur` (`siren`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm`.`facturation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm`.`facturation` (
  `contact_id` INT NOT NULL,
  `facture_num_facture` INT NOT NULL,
  PRIMARY KEY (`contact_id`, `facture_num_facture`),
  INDEX `fk_contact_has_facture_facture1_idx` (`facture_num_facture` ASC),
  INDEX `fk_contact_has_facture_contact1_idx` (`contact_id` ASC),
  CONSTRAINT `fk_contact_has_facture_contact1`
    FOREIGN KEY (`contact_id`)
    REFERENCES `crm`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_has_facture_facture1`
    FOREIGN KEY (`facture_num_facture`)
    REFERENCES `crm`.`facture` (`num_facture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
